[package]
name = "fhec-bind"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "symbols, scopes, imports, inheritance"

[dependencies]
solar-ast = { path = "../vendor/solar-ast" }
solar-interface = { path = "../vendor/solar-interface" }
solar-data-structures = { path = "../vendor/solar-data-structures" }

[dev-dependencies]
solar-parse = { path = "../vendor/solar-parse" }
