[package]
name = "fhec-bind"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "symbols, scopes, imports, inheritance"

[dependencies]
solar-ast.workspace = true
solar-interface.workspace = true
solar-data-structures.workspace = true

[dev-dependencies]
solar-parse.workspace = true
